[theme]
primaryColor="#b2ffff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0ffff"
textColor="#252525"
font="serif"

GROQ_API_KEY = "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"
